# Generated by Django 4.0.1 on 2022-01-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_media_path_alter_media_views_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.FloatField(),
        ),
    ]
